language: android

android:
  components:
    - android-28
    - build-tools-28.0.3
    - tools
    - platform-tools
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-29"
  - chmod +x gradlew

script:
  - ./gradlew clean assembleDebug assembleRelease testDebug
