language: android

android:
  components:
    - build-tools-29.0.2
    - android-29
    - tools
    - platform-tools
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-29"
  - chmod +x gradlew

script:
   - ./gradlew clean build
