language: android

android:
  components:
    - android-29
    - build-tools-29.0.2
    - tools
    - platform-tools
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-29"
  - chmod +x gradlew

script:
  - ./gradlew clean assembleDebug assembleRelease testDebug